version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: tickhelp
      POSTGRES_USER: tickhelp
      POSTGRES_PASSWORD: tickhelp
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tickhelp.com
      PGADMIN_DEFAULT_PASSWORD: tickhelp
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  pgdata:
